version: '3'

services:
  harbour:
    build:
      context: .
      dockerfile: ./docker/harbour/Dockerfile
    ports:
      - "8098:8098"
    links:
      - database:database
  database:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    ports:
      - "3307:3306"
    #    volumes:ß
    #      - ./docker/database/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=freightmate-core
      - MYSQL_USER=freightmate
      - MYSQL_PASSWORD=freightmate
      - MYSQL_ROOT_PASSWORD=freightmate