package com.freightmate.harbour.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Address {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private AddressType addressType;

    @ManyToOne(fetch = FetchType.LAZY)
    private User customer; // the table needs to have column name customer_id

    @ManyToOne(fetch = FetchType.LAZY)
    private User client;

    private String referenceId;

    @Column(nullable = false)
    private String companyName;

    @Column(nullable = false)
    private String addressLine1;

    private String addressLine2;

    @Column(nullable = false)
    private String town;

    @Column(nullable = false)
    //@Size(max = 4, min = 3)       // Commented, existing data contains LENGTH(postcode) > 4
    private int postcode;

    @Column(nullable = false)
    private String country;

    @Column(nullable = false)
    private String state;           // State is not using enum due to existing data

    @Column(nullable = false)
    private String contactName;

    private String contactNo;

    private String contactEmail;

    private String notes; // Special Instructions

    @Column(nullable = false)
    private Boolean isDefault;

    private int countUsed;

    @Column(nullable = false)
    Boolean isDeleted;
    LocalDateTime deletedAt;

    @CreationTimestamp
    LocalDateTime createdAt;
    @UpdateTimestamp
    LocalDateTime updatedAt;

    // todo Add a updated by column to cover devs/admins/autogenerated updated by logic
    // https://stackoverflow.com/a/42165624 provides a nice example with spring security
    String deletedBy;
    String createdBy;
    String updatedBy;
}
