package com.freightmate.harbour.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import java.time.LocalDateTime;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Getter
@Setter
public class Consignment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @JsonIgnore
    @ManyToOne(targetEntity = User.class, fetch = FetchType.LAZY)
    private User client;

    @Column(name = "client_id", insertable = false, updatable = false)
    private long clientId;

    @JsonIgnore
    @ManyToOne(targetEntity = Address.class, fetch = FetchType.LAZY)
    private Address senderAddress;

    @Column(name = "sender_address_id", insertable = false, updatable = false)
    private long senderAddressId;

    @JsonIgnore
    @ManyToOne(targetEntity = Address.class, fetch = FetchType.LAZY)
    private Address deliveryAddress;

    @Column(name = "delivery_address_id", insertable = false, updatable = false)
    private long deliveryAddressId;

    private String connoteId;

    private LocalDateTime dispatchDateAt;
    private LocalDateTime deliveryWindowStartAt;
    private LocalDateTime deliveryWindowEndAt;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private AddressClass addressClass;

    @Column(nullable = false)
    @ColumnDefault(value = "false")
    private Boolean isAllowedToLeave;

    @Column(nullable = false)
    @ColumnDefault(value = "false")
    private Boolean isTailgateRequired;

    @Column(nullable = false)
    @ColumnDefault(value = "false")
    Boolean isDeleted;

    LocalDateTime deletedAt;

    @CreationTimestamp
    LocalDateTime createdAt;

    @UpdateTimestamp
    LocalDateTime updatedAt;

    // todo Add a updated by column to cover devs/admins/autogenerated updated by logic
    // https://stackoverflow.com/a/42165624 provides a nice example with spring security
    String deletedBy;
    String createdBy;
    String updatedBy;
}
