-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 18:53:53 2020
-- Model: FM DB Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema freightmate
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `freightmate` ;

-- -----------------------------------------------------
-- Schema freightmate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freightmate` DEFAULT CHARACTER SET utf8 ;
USE `freightmate` ;

-- -----------------------------------------------------
-- Table `freightmate`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`user` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `preferred_unit` VARCHAR(45) NULL DEFAULT 'M',
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  `token` VARCHAR(255) NULL,
  `token_created_at` DATETIME NULL,
  `original_id` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_user_user1_idx` (`created_by` ASC),
  INDEX `fk_user_user2_idx` (`updated_by` ASC),
  INDEX `fk_user_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Consolidates attributes that are common across all users in the system.';


-- -----------------------------------------------------
-- Table `freightmate`.`user_broker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`user_broker` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`user_broker` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `bookings_email` VARCHAR(255) NULL,
  `service_email` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NOT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  INDEX `fk_user_broker_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_user_broker_user2_idx` (`created_by` ASC),
  INDEX `fk_user_broker_user3_idx` (`updated_by` ASC),
  INDEX `fk_user_broker_user4_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_user_broker_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_broker_user2`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_broker_user3`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_broker_user4`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Role entity containing attributes that are exclusive to Brokers and to act as an instance of a Broker within the data layer, inheriting common user attributes.';


-- -----------------------------------------------------
-- Table `freightmate`.`user_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`user_customer` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`user_customer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `user_broker_id` INT UNSIGNED NULL,
  `is_manifesting_active` TINYINT NULL DEFAULT 0,
  `goods_pickup` TINYINT NULL DEFAULT 0,
  `status` TINYINT NULL DEFAULT 0,
  `shared_address` TINYINT NULL DEFAULT 0,
  `dispatch_date_rollover` TINYINT NULL DEFAULT 0,
  `notification_email` TINYINT NULL DEFAULT 0,
  `service` TINYINT NULL DEFAULT 0,
  `consolidation` TINYINT NULL DEFAULT 0,
  `difot` TINYINT NULL DEFAULT 0,
  `pickup_cut_off` TINYINT NULL DEFAULT 0,
  `extended_labels` TINYINT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  INDEX `fk_user_customer_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_user_customer_user_broker1_idx` (`user_broker_id` ASC),
  INDEX `fk_user_customer_user2_idx` (`created_by` ASC),
  INDEX `fk_user_customer_user3_idx` (`updated_by` ASC),
  INDEX `fk_user_customer_user4_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_user_customer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_customer_user_broker1`
    FOREIGN KEY (`user_broker_id`)
    REFERENCES `freightmate`.`user_broker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_customer_user2`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_customer_user3`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_customer_user4`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Role entity containing attributes that are exclusive to Customers and to act as an instance of a Customer within the data layer, inheriting common user attributes.';


-- -----------------------------------------------------
-- Table `freightmate`.`user_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`user_client` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`user_client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `user_customer_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  INDEX `fk_user_client_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_user_client_user_customer1_idx` (`user_customer_id` ASC),
  INDEX `fk_user_client_user2_idx` (`created_by` ASC),
  INDEX `fk_user_client_user3_idx` (`updated_by` ASC),
  INDEX `fk_user_client_user4_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_user_client_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_client_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_client_user2`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_client_user3`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_client_user4`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Role entity containing attributes that are exclusive to Clients and to act as an instance of a Client within the data layer, inheriting common user attributes.';


-- -----------------------------------------------------
-- Table `freightmate`.`suburb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`suburb` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`suburb` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `postcode` INT UNSIGNED NOT NULL,
  `state` CHAR(3) NULL,
  `country` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suburb_user1_idx` (`created_by` ASC),
  INDEX `fk_suburb_user2_idx` (`updated_by` ASC),
  INDEX `fk_suburb_user3_idx` (`deleted_by` ASC),
  UNIQUE INDEX `name_postcode_UNIQUE` (`name` ASC, `postcode` ASC),
  CONSTRAINT `fk_suburb_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suburb_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suburb_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains data about all suburbs served by the system.';


-- -----------------------------------------------------
-- Table `freightmate`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`address` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_broker_id` INT UNSIGNED NULL,
  `user_customer_id` INT UNSIGNED NULL,
  `user_client_id` INT UNSIGNED NULL,
  `address_type` ENUM('DELIVERY', 'SENDER') NOT NULL,
  `address_line_1` VARCHAR(255) NOT NULL,
  `address_line_2` VARCHAR(255) NULL,
  `company` VARCHAR(45) NULL,
  `suburb_id` INT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NULL,
  `special_instructions` VARCHAR(255) NULL,
  `phone_number` VARCHAR(45) NULL,
  `contact_name` VARCHAR(255) NULL,
  `is_default` TINYINT NOT NULL DEFAULT 0,
  `reference_id` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_user_customer1_idx` (`user_customer_id` ASC),
  INDEX `fk_address_user_client1_idx` (`user_client_id` ASC),
  INDEX `fk_address_user_broker1_idx` (`user_broker_id` ASC),
  INDEX `fk_address_suburb1_idx` (`suburb_id` ASC),
  INDEX `fk_address_user1_idx` (`created_by` ASC),
  INDEX `fk_address_user2_idx` (`updated_by` ASC),
  INDEX `fk_address_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_address_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_user_client1`
    FOREIGN KEY (`user_client_id`)
    REFERENCES `freightmate`.`user_client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_user_broker1`
    FOREIGN KEY (`user_broker_id`)
    REFERENCES `freightmate`.`user_broker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_suburb1`
    FOREIGN KEY (`suburb_id`)
    REFERENCES `freightmate`.`suburb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains customers\' and clients\' addresses and their attributes.';


-- -----------------------------------------------------
-- Table `freightmate`.`quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`quote` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`quote` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender_address_id` INT UNSIGNED NOT NULL,
  `delivery_address_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `total` VARCHAR(255) NULL DEFAULT NULL,
  `quantity` FLOAT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `authority_to_leave` TINYINT(1) NULL DEFAULT '0',
  `tailgate_required` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quote_address1_idx` (`sender_address_id` ASC),
  INDEX `fk_quote_address2_idx` (`delivery_address_id` ASC),
  INDEX `fk_quote_user1_idx` (`created_by` ASC),
  INDEX `fk_quote_user2_idx` (`updated_by` ASC),
  INDEX `fk_quote_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_quote_address1`
    FOREIGN KEY (`sender_address_id`)
    REFERENCES `freightmate`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quote_address2`
    FOREIGN KEY (`delivery_address_id`)
    REFERENCES `freightmate`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quote_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quote_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quote_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains data persisted from quick quotes generated in the system.';


-- -----------------------------------------------------
-- Table `freightmate`.`manifest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`manifest` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`manifest` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `goods_pickup_status` TINYINT NULL DEFAULT NULL COMMENT 'if the customer has the goods pickup flag on then this will be set to 0 and will appear on a popup on all screens for that customer/client where they can tick off that their goods have been picked up. Used for food related items to remind them to send em off',
  `manifest_number` VARCHAR(255) NULL DEFAULT NULL COMMENT 'where carriers generate their own manifest number we store it here to use in data transfers and labels',
  `ready_time` VARCHAR(10) NULL DEFAULT NULL,
  `closing_time` VARCHAR(10) NULL DEFAULT NULL,
  `data_status` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_manifest_user1_idx` (`created_by` ASC),
  INDEX `fk_manifest_user2_idx` (`updated_by` ASC),
  INDEX `fk_manifest_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_manifest_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manifest_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manifest_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains manifests and their attributes.';


-- -----------------------------------------------------
-- Table `freightmate`.`consignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`consignment` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`consignment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_client_id` INT UNSIGNED NOT NULL,
  `quote_id` INT UNSIGNED NULL,
  `manifest_id` INT UNSIGNED NULL,
  `sender_address_id` INT UNSIGNED NOT NULL,
  `delivery_address_id` INT UNSIGNED NOT NULL,
  `delivery_address_class` ENUM('RESIDENTIAL', 'BUSINESS') NULL DEFAULT 'BUSINESS',
  `connote_number` VARCHAR(255) NULL DEFAULT NULL,
  `who_pays` VARCHAR(255) NULL DEFAULT NULL,
  `payment_account_number` VARCHAR(255) NULL DEFAULT NULL,
  `authority_to_leave` TINYINT(1) NULL DEFAULT NULL,
  `delivery_window_begin` DATETIME NULL DEFAULT NULL,
  `delivery_window_end` DATETIME NULL DEFAULT NULL,
  `special_instructions` VARCHAR(255) NULL DEFAULT NULL,
  `scale_from` FLOAT NULL DEFAULT NULL,
  `scale_to` FLOAT NULL DEFAULT NULL,
  `base_charge` FLOAT NULL DEFAULT NULL,
  `rate_charge` FLOAT NULL DEFAULT NULL,
  `min_charge` FLOAT NULL DEFAULT NULL,
  `fuel` FLOAT NULL DEFAULT NULL,
  `cubic_conversion_rate` FLOAT NULL DEFAULT NULL,
  `consignment_type` ENUM('DEFAULT', 'RETURN', 'THIRD_PARTY') NULL DEFAULT NULL,
  `residential_address_charge` FLOAT NULL DEFAULT NULL,
  `is_tailgate_required` TINYINT NULL DEFAULT 0,
  `tailgate_charge` FLOAT NULL DEFAULT NULL,
  `dg_charge` FLOAT NULL DEFAULT NULL,
  `oversize_charge` FLOAT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `status_booked` DATETIME NULL DEFAULT NULL,
  `status_in_transit` DATETIME NULL DEFAULT NULL,
  `status_out_for_delivery` DATETIME NULL DEFAULT NULL,
  `status_delivered` DATETIME NULL DEFAULT NULL,
  `status_unable_to_deliver` DATETIME NULL DEFAULT NULL,
  `status_note` VARCHAR(255) NULL DEFAULT NULL,
  `status_late` TINYINT(1) NULL DEFAULT NULL,
  `status_latest_timestamp` DATETIME NULL DEFAULT NULL,
  `total_item_weight` FLOAT NULL DEFAULT NULL,
  `total_item_cubic` FLOAT NULL DEFAULT NULL,
  `total_item_qty` INT(11) NULL DEFAULT NULL,
  `freight_cost` FLOAT NULL DEFAULT NULL,
  `cat_1_fee` FLOAT NULL DEFAULT NULL,
  `fuel_levy` FLOAT NULL DEFAULT NULL,
  `cat_2_fee` FLOAT NULL DEFAULT NULL,
  `gst` FLOAT NULL DEFAULT NULL,
  `total_cost` FLOAT NULL DEFAULT NULL,
  `poa` TINYINT(1) NULL DEFAULT NULL,
  `service_title_1` VARCHAR(255) NULL DEFAULT NULL,
  `service_title_2` VARCHAR(255) NULL DEFAULT NULL,
  `service_title_3` VARCHAR(255) NULL DEFAULT NULL,
  `dispatched_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consignment_quote1_idx` (`quote_id` ASC),
  INDEX `fk_consignment_manifest1_idx` (`manifest_id` ASC),
  INDEX `fk_consignment_address1_idx` (`sender_address_id` ASC),
  INDEX `fk_consignment_address2_idx` (`delivery_address_id` ASC),
  INDEX `fk_consignment_user1_idx` (`created_by` ASC),
  INDEX `fk_consignment_user2_idx` (`updated_by` ASC),
  INDEX `fk_consignment_user3_idx` (`deleted_by` ASC),
  INDEX `fk_consignment_user_client1_idx` (`user_client_id` ASC),
  CONSTRAINT `fk_consignment_quote1`
    FOREIGN KEY (`quote_id`)
    REFERENCES `freightmate`.`quote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_manifest1`
    FOREIGN KEY (`manifest_id`)
    REFERENCES `freightmate`.`manifest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_address1`
    FOREIGN KEY (`sender_address_id`)
    REFERENCES `freightmate`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_address2`
    FOREIGN KEY (`delivery_address_id`)
    REFERENCES `freightmate`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_user_client1`
    FOREIGN KEY (`user_client_id`)
    REFERENCES `freightmate`.`user_client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains data for generated consignments.';


-- -----------------------------------------------------
-- Table `freightmate`.`carrier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`carrier` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`carrier` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NULL,
  `is_data_transfer_required` TINYINT NOT NULL DEFAULT 0,
  `data_transfer_frequency` ENUM('DAILY', 'INSTANT') NULL,
  `label_type` ENUM('CUSTOM', 'GENERIC') NULL,
  `has_suburb_surcharge` TINYINT NOT NULL DEFAULT 0,
  `has_sender_id` TINYINT NOT NULL DEFAULT 0,
  `service_types` JSON NULL,
  `pricing` JSON NULL,
  `metro_zones` JSON NULL,
  `is_internal_invoicing` TINYINT NOT NULL DEFAULT 0,
  `is_tracking_difot` TINYINT NOT NULL DEFAULT 0,
  `tracking_url` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrier_user1_idx` (`created_by` ASC),
  INDEX `fk_carrier_user2_idx` (`updated_by` ASC),
  INDEX `fk_carrier_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_carrier_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains common attributes across all carriers.';


-- -----------------------------------------------------
-- Table `freightmate`.`carrier_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`carrier_account` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`carrier_account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_number` VARCHAR(45) NOT NULL,
  `carrier_id` INT UNSIGNED NOT NULL,
  `user_broker_id` INT UNSIGNED NULL,
  `user_customer_id` INT UNSIGNED NULL,
  `source_account_id` INT UNSIGNED NULL,
  `is_default` TINYINT NOT NULL,
  `rule_res_address_cost` FLOAT NULL DEFAULT NULL,
  `rule_tailgate_cost` FLOAT NULL DEFAULT NULL,
  `rule_dg_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat1_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat2_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat3_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat4_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat5_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat1_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat2_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat3_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat4_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat5_size` FLOAT NULL DEFAULT NULL,
  `rule_manual_handling_max_l` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_max_w` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_max_h` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_min_kg` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_max_kg` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_charge_per` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_charge` VARCHAR(255) NULL DEFAULT NULL,
  `fuel` FLOAT NULL DEFAULT NULL,
  `per_kg_cubic` FLOAT NULL DEFAULT NULL,
  `carton_cubic` FLOAT NULL DEFAULT NULL,
  `carton_max_h` FLOAT NULL DEFAULT NULL,
  `carton_max_l` FLOAT NULL DEFAULT NULL,
  `carton_max_w` FLOAT NULL DEFAULT NULL,
  `carton_max_kg` FLOAT NULL DEFAULT NULL,
  `pallet_cubic` FLOAT NULL DEFAULT NULL,
  `pallet_max_h` FLOAT NULL DEFAULT NULL,
  `pallet_max_l` FLOAT NULL DEFAULT NULL,
  `pallet_max_w` FLOAT NULL DEFAULT NULL,
  `pallet_max_kg` FLOAT NULL DEFAULT NULL,
  `carton_average_weight` FLOAT NULL DEFAULT NULL,
  `pallet_overcharge` VARCHAR(20) NULL DEFAULT NULL,
  `half_pallet_max_h` FLOAT NULL DEFAULT NULL,
  `half_pallet_max_l` FLOAT NULL DEFAULT NULL,
  `half_pallet_max_w` FLOAT NULL DEFAULT NULL,
  `half_pallet_max_kg` FLOAT NULL DEFAULT NULL,
  `rule_cat_format_1` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_2` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_3` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_4` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_5` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrier_rules_user_broker1_idx` (`user_broker_id` ASC),
  INDEX `fk_carrier_rules_user_customer1_idx` (`user_customer_id` ASC),
  INDEX `fk_carrier_rules_carrier1_idx` (`carrier_id` ASC),
  INDEX `fk_carrier_account_user1_idx` (`created_by` ASC),
  INDEX `fk_carrier_account_user2_idx` (`updated_by` ASC),
  INDEX `fk_carrier_account_user3_idx` (`deleted_by` ASC),
  INDEX `fk_carrier_account_carrier_account1_idx` (`source_account_id` ASC),
  CONSTRAINT `fk_carrier_rules_user_broker1`
    FOREIGN KEY (`user_broker_id`)
    REFERENCES `freightmate`.`user_broker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_rules_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_rules_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `freightmate`.`carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_account_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_account_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_account_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_account_carrier_account1`
    FOREIGN KEY (`source_account_id`)
    REFERENCES `freightmate`.`carrier_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Instantiates, into account numbers, the relationships between carriers and customers, and carriers and brokers, and all the attributes related to those relationships, such as the consignment rules for pricing.';


-- -----------------------------------------------------
-- Table `freightmate`.`carrier_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`carrier_zone` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`carrier_zone` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carrier_account_id` INT UNSIGNED NOT NULL,
  `suburb_id` INT UNSIGNED NOT NULL,
  `zone` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrier_zone_carrier_account1_idx` (`carrier_account_id` ASC),
  INDEX `fk_carrier_zone_suburb1_idx` (`suburb_id` ASC),
  INDEX `fk_carrier_zone_user1_idx` (`created_by` ASC),
  INDEX `fk_carrier_zone_user2_idx` (`updated_by` ASC),
  INDEX `fk_carrier_zone_user3_idx` (`deleted_by` ASC),
  UNIQUE INDEX `carrier_account_id_suburb_id_UNIQUE` (`carrier_account_id` ASC, `suburb_id` ASC),
  CONSTRAINT `fk_carrier_zone_carrier_account1`
    FOREIGN KEY (`carrier_account_id`)
    REFERENCES `freightmate`.`carrier_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_zone_suburb1`
    FOREIGN KEY (`suburb_id`)
    REFERENCES `freightmate`.`suburb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_zone_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_zone_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_zone_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains the attributes related to geographical zones served by the carriers for each relationship with customers and/or brokers.';


-- -----------------------------------------------------
-- Table `freightmate`.`carrier_service_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`carrier_service_type` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`carrier_service_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carrier_id` INT UNSIGNED NOT NULL,
  `service_type` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  INDEX `fk_carrier_service_type_carrier1_idx` (`carrier_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_carrier_service_type_user1_idx` (`created_by` ASC),
  INDEX `fk_carrier_service_type_user2_idx` (`updated_by` ASC),
  INDEX `fk_carrier_service_type_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_carrier_service_type_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `freightmate`.`carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_service_type_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_service_type_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrier_service_type_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freightmate`.`rate_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`rate_card` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`rate_card` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carrier_account_id` INT UNSIGNED NOT NULL,
  `carrier_service_type_id` INT UNSIGNED NOT NULL,
  `from_carrier_zone_id` INT UNSIGNED NOT NULL,
  `to_carrier_zone_id` INT UNSIGNED NOT NULL,
  `weight_break_1` FLOAT NOT NULL,
  `weight_break_2` FLOAT NOT NULL,
  `weight_break_3` FLOAT NOT NULL,
  `weight_break_4` FLOAT NOT NULL,
  `weight_break_5` FLOAT NOT NULL,
  `space_break_1` FLOAT NULL DEFAULT NULL,
  `space_break_2` FLOAT NULL DEFAULT NULL,
  `space_break_3` FLOAT NULL DEFAULT NULL,
  `space_break_4` FLOAT NULL DEFAULT NULL,
  `space_break_5` FLOAT NULL DEFAULT NULL,
  `space_break_6` FLOAT NULL DEFAULT NULL,
  `sell_base_rate` FLOAT NULL DEFAULT NULL,
  `sell_per_kg_rate_1` FLOAT NULL DEFAULT NULL,
  `sell_per_kg_rate_2` FLOAT NULL DEFAULT NULL,
  `sell_per_kg_rate_3` FLOAT NULL DEFAULT NULL,
  `sell_per_kg_rate_4` FLOAT NULL DEFAULT NULL,
  `sell_per_kg_rate_5` FLOAT NULL DEFAULT NULL,
  `sell_min_rate` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_half` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_half_2` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_half_3` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_half_4` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_half_5` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_half_6` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_full` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_full_2` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_full_3` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_full_4` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_full_5` FLOAT NULL DEFAULT NULL,
  `sell_dry_pallet_full_6` FLOAT NULL DEFAULT NULL,
  `sell_space_rate_1` FLOAT NULL DEFAULT NULL,
  `sell_space_rate_2` FLOAT NULL DEFAULT NULL,
  `sell_space_rate_3` FLOAT NULL DEFAULT NULL,
  `sell_space_rate_4` FLOAT NULL DEFAULT NULL,
  `sell_space_rate_5` FLOAT NULL DEFAULT NULL,
  `sell_space_rate_6` FLOAT NULL DEFAULT NULL,
  `full_pallet_break_1` FLOAT NULL DEFAULT NULL,
  `full_pallet_break_2` FLOAT NULL DEFAULT NULL,
  `full_pallet_break_3` FLOAT NULL DEFAULT NULL,
  `full_pallet_break_4` FLOAT NULL DEFAULT NULL,
  `full_pallet_break_5` FLOAT NULL DEFAULT NULL,
  `full_pallet_break_6` FLOAT NULL DEFAULT NULL,
  `half_pallet_break_1` FLOAT NULL DEFAULT NULL,
  `half_pallet_break_2` FLOAT NULL DEFAULT NULL,
  `half_pallet_break_3` FLOAT NULL DEFAULT NULL,
  `half_pallet_break_4` FLOAT NULL DEFAULT NULL,
  `half_pallet_break_5` FLOAT NULL DEFAULT NULL,
  `half_pallet_break_6` FLOAT NULL DEFAULT NULL,
  `sell_skid` FLOAT NULL DEFAULT NULL,
  `sell_carton` FLOAT NULL DEFAULT NULL,
  `sell_cubic` FLOAT NULL DEFAULT '0',
  `sell_national_satchel_1kg` FLOAT NULL DEFAULT NULL,
  `sell_national_satchel_3kg` FLOAT NULL DEFAULT NULL,
  `sell_national_satchel_5kg` FLOAT NULL DEFAULT NULL,
  `sell_optical_satchel_05kg` FLOAT NULL DEFAULT NULL,
  `sell_optical_satchel_3kg` FLOAT NULL DEFAULT NULL,
  `sell_label_3kg` FLOAT NULL DEFAULT NULL,
  `sheet_no` INT(11) NULL DEFAULT NULL,
  `sell_carton_rate_1` FLOAT NULL DEFAULT NULL,
  `sell_carton_rate_2` FLOAT NULL DEFAULT NULL,
  `sell_carton_rate_3` FLOAT NULL DEFAULT NULL,
  `sell_carton_rate_4` FLOAT NULL DEFAULT NULL,
  `sell_carton_rate_5` FLOAT NULL DEFAULT NULL,
  `sell_carton_rate_6` FLOAT NULL DEFAULT NULL,
  `sell_carton_break_1` FLOAT NULL DEFAULT NULL,
  `sell_carton_break_2` FLOAT NULL DEFAULT NULL,
  `sell_carton_break_3` FLOAT NULL DEFAULT NULL,
  `sell_carton_break_4` FLOAT NULL DEFAULT NULL,
  `sell_carton_break_5` FLOAT NULL DEFAULT NULL,
  `sell_carton_break_6` FLOAT NULL DEFAULT NULL,
  `sell_taxi_truck_hourly_2t` FLOAT NULL,
  `sell_taxi_truck_hourly_4t` FLOAT NULL,
  `sell_taxi_truck_hourly_6t` FLOAT NULL,
  `sell_taxi_truck_hourly_8t` FLOAT NULL,
  `sell_taxi_truck_hourly_12t` FLOAT NULL,
  `sell_taxi_truck_hourly_14t` FLOAT NULL,
  `sell_taxi_truck_hourly_semi` FLOAT NULL,
  `sell_taxi_truck_hourly_bdouble` FLOAT NULL,
  `sell_courier_c` FLOAT NULL,
  `sell_courier_svt` FLOAT NULL,
  `sell_courier_1vt` FLOAT NULL,
  `sell_courier_1r` FLOAT NULL,
  `sell_courier_2t` FLOAT NULL,
  `sell_courier_4t` FLOAT NULL,
  `sell_courier_6t` FLOAT NULL,
  `sell_courier_8t` FLOAT NULL,
  `sell_courier_12t` FLOAT NULL,
  `sell_courier_14t` FLOAT NULL,
  `sell_semi` FLOAT NULL,
  `sell_bdouble` FLOAT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rate_card_carrier_service_type1_idx` (`carrier_service_type_id` ASC),
  INDEX `fk_rate_card_carrier_zone1_idx` (`from_carrier_zone_id` ASC),
  INDEX `fk_rate_card_carrier_zone2_idx` (`to_carrier_zone_id` ASC),
  INDEX `fk_rate_card_user1_idx` (`created_by` ASC),
  INDEX `fk_rate_card_user2_idx` (`updated_by` ASC),
  INDEX `fk_rate_card_user3_idx` (`deleted_by` ASC),
  INDEX `fk_rate_card_carrier_account1_idx` (`carrier_account_id` ASC),
  CONSTRAINT `fk_rate_card_carrier_service_type1`
    FOREIGN KEY (`carrier_service_type_id`)
    REFERENCES `freightmate`.`carrier_service_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_card_carrier_zone1`
    FOREIGN KEY (`from_carrier_zone_id`)
    REFERENCES `freightmate`.`carrier_zone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_card_carrier_zone2`
    FOREIGN KEY (`to_carrier_zone_id`)
    REFERENCES `freightmate`.`carrier_zone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_card_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_card_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_card_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_card_carrier_account1`
    FOREIGN KEY (`carrier_account_id`)
    REFERENCES `freightmate`.`carrier_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains the pricing for rate costs, per carrier service type and carrier-customer or carrier-broker relationship.';


-- -----------------------------------------------------
-- Table `freightmate`.`transit_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`transit_time` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`transit_time` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carrier_id` INT UNSIGNED NOT NULL,
  `carrier_service_type_id` INT UNSIGNED NOT NULL,
  `MEL_Metro` INT UNSIGNED NULL DEFAULT NULL,
  `SYD_Metro` INT UNSIGNED NULL DEFAULT NULL,
  `BRS_Metro` INT UNSIGNED NULL DEFAULT NULL,
  `PER_Metro` INT UNSIGNED NULL DEFAULT NULL,
  `ADL_Metro` INT UNSIGNED NULL DEFAULT NULL,
  `GEE_Metro` INT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transit_time_carrier1_idx` (`carrier_id` ASC),
  INDEX `fk_transit_time_carrier_service_type1_idx` (`carrier_service_type_id` ASC),
  INDEX `fk_transit_time_user1_idx` (`created_by` ASC),
  INDEX `fk_transit_time_user2_idx` (`updated_by` ASC),
  INDEX `fk_transit_time_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_transit_time_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `freightmate`.`carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transit_time_carrier_service_type1`
    FOREIGN KEY (`carrier_service_type_id`)
    REFERENCES `freightmate`.`carrier_service_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transit_time_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transit_time_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transit_time_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains transit time, in days, from destination suburbs (rows) into metro zones (columns), for each carrier.';


-- -----------------------------------------------------
-- Table `freightmate`.`item_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`item_type` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`item_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `is_mutable` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_type_user3_idx` (`deleted_by` ASC),
  INDEX `fk_item_type_user1_idx` (`created_by` ASC),
  INDEX `fk_item_type_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_item_type_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_type_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_type_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Stores the item types';


-- -----------------------------------------------------
-- Table `freightmate`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`item` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `consignment_id` INT UNSIGNED NULL,
  `quote_id` INT UNSIGNED NULL,
  `item_type_id` INT UNSIGNED NOT NULL,
  `length` FLOAT NOT NULL,
  `height` FLOAT NOT NULL,
  `width` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  `total_weight` FLOAT NOT NULL,
  `volume` FLOAT NOT NULL,
  `is_hazardous` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_consignment1_idx` (`consignment_id` ASC),
  INDEX `fk_item_quote1_idx` (`quote_id` ASC),
  INDEX `fk_item_user1_idx` (`created_by` ASC),
  INDEX `fk_item_user2_idx` (`updated_by` ASC),
  INDEX `fk_item_user3_idx` (`deleted_by` ASC),
  INDEX `fk_item_item_type1_idx` (`item_type_id` ASC),
  CONSTRAINT `fk_item_consignment1`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `freightmate`.`consignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_quote1`
    FOREIGN KEY (`quote_id`)
    REFERENCES `freightmate`.`quote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_item_type1`
    FOREIGN KEY (`item_type_id`)
    REFERENCES `freightmate`.`item_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Instantiates an item based on an item template (item_template)';


-- -----------------------------------------------------
-- Table `freightmate`.`un_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`un_number` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`un_number` (
  `number` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(45) NULL,
  `proper_shipping_name` VARCHAR(400) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`number`),
  INDEX `fk_un_number_user1_idx` (`created_by` ASC),
  INDEX `fk_un_number_user2_idx` (`updated_by` ASC),
  INDEX `fk_un_number_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_un_number_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_un_number_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_un_number_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'The United Nations identifier that is given to hazardous and dangerous materials.';


-- -----------------------------------------------------
-- Table `freightmate`.`dangerous_good`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`dangerous_good` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`dangerous_good` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `un_number` INT UNSIGNED NOT NULL,
  `type_of_packaging` VARCHAR(255) NULL DEFAULT NULL,
  `weight` FLOAT NULL DEFAULT NULL,
  `shipping_name` VARCHAR(255) NULL DEFAULT 'Example Proper Shipping Name',
  `common_name` VARCHAR(255) NULL DEFAULT NULL,
  `hazard_class` VARCHAR(45) NULL,
  `sub_risk` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dangerous_good_item1_idx` (`item_id` ASC),
  INDEX `fk_dangerous_good_un_number1_idx` (`un_number` ASC),
  INDEX `fk_dangerous_good_user1_idx` (`created_by` ASC),
  INDEX `fk_dangerous_good_user2_idx` (`updated_by` ASC),
  INDEX `fk_dangerous_good_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_dangerous_good_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `freightmate`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_un_number1`
    FOREIGN KEY (`un_number`)
    REFERENCES `freightmate`.`un_number` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Instantiates a dangerous good based on a template (dangerous_good_template)';


-- -----------------------------------------------------
-- Table `freightmate`.`email_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`email_template` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`email_template` (
  `user_client_id` INT UNSIGNED NOT NULL,
  `company_name` VARCHAR(255) NULL DEFAULT NULL,
  `logo_image_filename` VARCHAR(255) NULL DEFAULT NULL,
  `logo_image_link` VARCHAR(255) NULL DEFAULT NULL,
  `logo_image_delete_hash` VARCHAR(255) NULL DEFAULT NULL,
  `footer_image_filename` VARCHAR(255) NULL DEFAULT NULL,
  `footer_image_link` VARCHAR(255) NULL DEFAULT NULL,
  `footer_image_delete_hash` VARCHAR(255) NULL DEFAULT NULL,
  `custom_text_area` TEXT NULL DEFAULT NULL,
  `contact_phone` VARCHAR(255) NULL DEFAULT NULL,
  `contact_email` VARCHAR(255) NULL DEFAULT NULL,
  `banner_text_colour` VARCHAR(255) NULL DEFAULT '#fdfdfd',
  `banner_background_colour` VARCHAR(255) NULL DEFAULT '#424a58',
  `body_heading_colour` VARCHAR(255) NULL DEFAULT '#666666',
  `body_text_colour` VARCHAR(255) NULL DEFAULT '#666666',
  `body_background_colour` VARCHAR(255) NULL DEFAULT '#f1f1f1',
  `block_text_colour` VARCHAR(255) NULL DEFAULT '#666666',
  `block_background_colour` VARCHAR(255) NULL DEFAULT '#ffffff',
  `logo_and_title` TINYINT NULL DEFAULT '0',
  `default_custom_email` TINYINT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`user_client_id`),
  INDEX `fk_email_template_user1_idx` (`created_by` ASC),
  INDEX `fk_email_template_user2_idx` (`updated_by` ASC),
  INDEX `fk_email_template_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_email_template_user_client1`
    FOREIGN KEY (`user_client_id`)
    REFERENCES `freightmate`.`user_client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_template_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_template_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_template_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains attributes for the custom emails that are sent to customers with every consignment.';


-- -----------------------------------------------------
-- Table `freightmate`.`suburb_surcharge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`suburb_surcharge` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`suburb_surcharge` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `carrier_id` INT UNSIGNED NOT NULL,
  `suburb_id` INT UNSIGNED NOT NULL,
  `surcharge` FLOAT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suburb_surcharge_carrier1_idx` (`carrier_id` ASC),
  INDEX `fk_suburb_surcharge_suburb1_idx` (`suburb_id` ASC),
  INDEX `fk_suburb_surcharge_user1_idx` (`created_by` ASC),
  INDEX `fk_suburb_surcharge_user2_idx` (`updated_by` ASC),
  INDEX `fk_suburb_surcharge_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_suburb_surcharge_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `freightmate`.`carrier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suburb_surcharge_suburb1`
    FOREIGN KEY (`suburb_id`)
    REFERENCES `freightmate`.`suburb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suburb_surcharge_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suburb_surcharge_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suburb_surcharge_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains surcharge values per suburb and carrier.';


-- -----------------------------------------------------
-- Table `freightmate`.`consignment_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`consignment_reference` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`consignment_reference` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `consignment_id` INT UNSIGNED NOT NULL,
  `description` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consignment_reference_consignment1_idx` (`consignment_id` ASC),
  INDEX `fk_consignment_reference_user1_idx` (`created_by` ASC),
  INDEX `fk_consignment_reference_user2_idx` (`updated_by` ASC),
  INDEX `fk_consignment_reference_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_consignment_reference_consignment1`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `freightmate`.`consignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_reference_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_reference_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consignment_reference_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains reference data related to consignments.';


-- -----------------------------------------------------
-- Table `freightmate`.`service_title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`service_title` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`service_title` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_customer_id` INT UNSIGNED NOT NULL,
  `order` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_title_user_customer1_idx` (`user_customer_id` ASC),
  INDEX `fk_service_title_user1_idx` (`created_by` ASC),
  INDEX `fk_service_title_user2_idx` (`updated_by` ASC),
  INDEX `fk_service_title_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_service_title_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_title_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_title_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_title_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains the titles of steps in the consignment processing (e.g. packed by).';


-- -----------------------------------------------------
-- Table `freightmate`.`servicing_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`servicing_name` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`servicing_name` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_customer_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicing_name_user_customer1_idx` (`user_customer_id` ASC),
  INDEX `fk_servicing_name_user1_idx` (`created_by` ASC),
  INDEX `fk_servicing_name_user2_idx` (`updated_by` ASC),
  INDEX `fk_servicing_name_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_servicing_name_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicing_name_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicing_name_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicing_name_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains the names of whoever can be selected in each of the service titles.';


-- -----------------------------------------------------
-- Table `freightmate`.`connote_account_variables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`connote_account_variables` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`connote_account_variables` (
  `carrier_account_id` INT UNSIGNED NOT NULL,
  `prefix` VARCHAR(10) NULL,
  `range_begin` INT(11) NULL DEFAULT NULL,
  `range_end` INT(11) NULL DEFAULT NULL,
  `latest_used_range_index` INT NULL DEFAULT NULL,
  `sender_id` VARCHAR(20) NULL DEFAULT NULL,
  `connote_abbreviation` VARCHAR(5) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`carrier_account_id`),
  INDEX `fk_connote_account_variables_user1_idx` (`created_by` ASC),
  INDEX `fk_connote_account_variables_user2_idx` (`updated_by` ASC),
  INDEX `fk_connote_account_variables_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_connote_account_variables_carrier_account1`
    FOREIGN KEY (`carrier_account_id`)
    REFERENCES `freightmate`.`carrier_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connote_account_variables_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connote_account_variables_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_connote_account_variables_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains the ID ranges for accounts to be created under each specific carrier-customer relationship.';


-- -----------------------------------------------------
-- Table `freightmate`.`variable_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`variable_template` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`variable_template` (
  `user_customer_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `scheduled_pickup` TINYINT(1) NULL DEFAULT NULL,
  `fuel` FLOAT NULL DEFAULT NULL,
  `per_kg_cubic` FLOAT NULL DEFAULT NULL,
  `carton_cubic` FLOAT NULL DEFAULT NULL,
  `carton_max_h` FLOAT NULL DEFAULT NULL,
  `carton_max_l` FLOAT NULL DEFAULT NULL,
  `carton_max_w` FLOAT NULL DEFAULT NULL,
  `carton_max_kg` FLOAT NULL DEFAULT NULL,
  `pallet_cubic` FLOAT NULL DEFAULT NULL,
  `pallet_max_h` FLOAT NULL DEFAULT NULL,
  `pallet_max_l` FLOAT NULL DEFAULT NULL,
  `pallet_max_w` FLOAT NULL DEFAULT NULL,
  `pallet_max_kg` FLOAT NULL DEFAULT NULL,
  `pallet_overcharge` VARCHAR(20) NULL DEFAULT NULL,
  `rule_res_address_cost` FLOAT NULL DEFAULT NULL,
  `rule_tailgate_cost` FLOAT NULL DEFAULT NULL,
  `rule_dg_cost` VARCHAR(10) NULL DEFAULT NULL,
  `rule_oversize_cat1_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat2_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat3_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat4_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat5_cost` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat1_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat2_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat3_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat4_size` FLOAT NULL DEFAULT NULL,
  `rule_oversize_cat5_size` FLOAT NULL DEFAULT NULL,
  `rule_cat_format_1` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_2` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_3` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_4` VARCHAR(20) NULL DEFAULT NULL,
  `rule_cat_format_5` VARCHAR(20) NULL DEFAULT NULL,
  `rule_manual_handling_max_l` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_max_w` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_max_h` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_min_kg` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_max_kg` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_charge_per` VARCHAR(255) NULL DEFAULT NULL,
  `rule_manual_handling_charge` VARCHAR(255) NULL DEFAULT NULL,
  `carton_average_weight` FLOAT NULL DEFAULT NULL,
  `half_pallet_max_l` FLOAT NULL DEFAULT NULL,
  `half_pallet_max_w` FLOAT NULL DEFAULT NULL,
  `half_pallet_max_h` FLOAT NULL DEFAULT NULL,
  `half_pallet_max_kg` FLOAT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`user_customer_id`),
  INDEX `fk_variable_template_user1_idx` (`created_by` ASC),
  INDEX `fk_variable_template_user2_idx` (`updated_by` ASC),
  INDEX `fk_variable_template_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_variable_template_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variable_template_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variable_template_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variable_template_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains attributes for specific templates to be displayed for the customer in the front-end.';


-- -----------------------------------------------------
-- Table `freightmate`.`item_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`item_template` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`item_template` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `length` FLOAT NOT NULL,
  `height` FLOAT NOT NULL,
  `width` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  `total_weight` FLOAT NOT NULL,
  `volume` FLOAT NOT NULL,
  `is_hazardous` TINYINT NOT NULL DEFAULT 0,
  `item_type_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_template_user1_idx` (`created_by` ASC),
  INDEX `fk_item_template_user2_idx` (`updated_by` ASC),
  INDEX `fk_item_template_user3_idx` (`deleted_by` ASC),
  INDEX `fk_item_template_item_type1_idx` (`item_type_id` ASC),
  CONSTRAINT `fk_item_template_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_template_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_template_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_template_item_type1`
    FOREIGN KEY (`item_type_id`)
    REFERENCES `freightmate`.`item_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Abstracts the available item types (some with pre-filled templates).';


-- -----------------------------------------------------
-- Table `freightmate`.`item_has_item_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`item_has_item_template` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`item_has_item_template` (
  `item_id` INT UNSIGNED NOT NULL,
  `item_template_id` INT UNSIGNED NOT NULL,
  `user_customer_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`item_id`, `item_template_id`),
  INDEX `fk_item_has_item_type_item_type1_idx` (`item_template_id` ASC),
  INDEX `fk_item_has_item_type_item1_idx` (`item_id` ASC),
  INDEX `fk_item_has_item_type_user_customer1_idx` (`user_customer_id` ASC),
  INDEX `fk_item_has_item_template_user1_idx` (`created_by` ASC),
  INDEX `fk_item_has_item_template_user2_idx` (`updated_by` ASC),
  INDEX `fk_item_has_item_template_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_item_has_item_type_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `freightmate`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_item_type_item_type1`
    FOREIGN KEY (`item_template_id`)
    REFERENCES `freightmate`.`item_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_item_type_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_item_template_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_item_template_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_item_template_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains the relationship between items, item templates and customers.';


-- -----------------------------------------------------
-- Table `freightmate`.`dangerous_good_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`dangerous_good_template` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`dangerous_good_template` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_template_id` INT UNSIGNED NOT NULL,
  `un_number` INT UNSIGNED NOT NULL,
  `type_of_packaging` VARCHAR(255) NULL DEFAULT NULL,
  `weight` FLOAT NULL DEFAULT NULL,
  `shipping_name` VARCHAR(255) NULL DEFAULT 'Example Proper Shipping Name',
  `common_name` VARCHAR(255) NULL DEFAULT NULL,
  `hazard_class` VARCHAR(45) NULL,
  `sub_risk` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dangerous_good_template_item_template1_idx` (`item_template_id` ASC),
  INDEX `fk_dangerous_good_template_un_number1_idx` (`un_number` ASC),
  INDEX `fk_dangerous_good_template_user1_idx` (`created_by` ASC),
  INDEX `fk_dangerous_good_template_user2_idx` (`updated_by` ASC),
  INDEX `fk_dangerous_good_template_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_dangerous_good_template_item_template1`
    FOREIGN KEY (`item_template_id`)
    REFERENCES `freightmate`.`item_template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_template_un_number1`
    FOREIGN KEY (`un_number`)
    REFERENCES `freightmate`.`un_number` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_template_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_template_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dangerous_good_template_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Abstracts the templates for dangerous goods within specific item templates.';


-- -----------------------------------------------------
-- Table `freightmate`.`item_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`item_number` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`item_number` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `user_client_id` INT UNSIGNED NOT NULL,
  `user_customer_id` INT UNSIGNED NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  INDEX `fk_item_number_item1_idx` (`item_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_item_number_user_client1_idx` (`user_client_id` ASC),
  INDEX `fk_item_number_user_customer1_idx` (`user_customer_id` ASC),
  INDEX `fk_item_number_user1_idx` (`created_by` ASC),
  INDEX `fk_item_number_user2_idx` (`updated_by` ASC),
  INDEX `fk_item_number_user3_idx` (`deleted_by` ASC),
  CONSTRAINT `fk_item_number_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `freightmate`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_number_user_client1`
    FOREIGN KEY (`user_client_id`)
    REFERENCES `freightmate`.`user_client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_number_user_customer1`
    FOREIGN KEY (`user_customer_id`)
    REFERENCES `freightmate`.`user_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_number_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_number_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_number_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Some carriers demand a unique identifier per item. This table stores them.';


-- -----------------------------------------------------
-- Table `freightmate`.`user_login_attempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`user_login_attempt` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`user_login_attempt` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `origin_ip` VARCHAR(30) NOT NULL,
  `success` TINYINT NOT NULL,
  `login_attempt_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Records the login attempts for audit purposes.';


-- -----------------------------------------------------
-- Table `freightmate`.`offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `freightmate`.`offer` ;

CREATE TABLE IF NOT EXISTS `freightmate`.`offer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quote_id` INT UNSIGNED NULL,
  `consignment_id` INT UNSIGNED NULL,
  `carrier_account_id` INT UNSIGNED NOT NULL,
  `eta` VARCHAR(10) NULL,
  `freight_cost` FLOAT NOT NULL,
  `category_1_fees` FLOAT NOT NULL DEFAULT 0,
  `category_2_fees` FLOAT NOT NULL DEFAULT 0,
  `fuel_surcharge` FLOAT NOT NULL DEFAULT 0,
  `gst` FLOAT NOT NULL,
  `total_cost` FLOAT NOT NULL,
  `selected` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `created_by` INT UNSIGNED NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  `updated_by` INT UNSIGNED NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NULL,
  `deleted_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offer_user1_idx` (`created_by` ASC),
  INDEX `fk_offer_user2_idx` (`updated_by` ASC),
  INDEX `fk_offer_user3_idx` (`deleted_by` ASC),
  INDEX `fk_offer_quote1_idx` (`quote_id` ASC),
  INDEX `fk_offer_consignment1_idx` (`consignment_id` ASC),
  INDEX `fk_offer_carrier_account1_idx` (`carrier_account_id` ASC),
  CONSTRAINT `fk_offer_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_user3`
    FOREIGN KEY (`deleted_by`)
    REFERENCES `freightmate`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_quote1`
    FOREIGN KEY (`quote_id`)
    REFERENCES `freightmate`.`quote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_consignment1`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `freightmate`.`consignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_carrier_account1`
    FOREIGN KEY (`carrier_account_id`)
    REFERENCES `freightmate`.`carrier_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains offers from carriers to specific quotes/consignments, through carrier accounts leveraging their rate cards.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
