-- MySQL Workbench Synchronization

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `freightmate`.`manifest` 
ADD COLUMN `user_client_id` INT(10) UNSIGNED NOT NULL AFTER `manifest_number`,
CHANGE COLUMN `manifest_number` `manifest_number` VARCHAR(255) NULL DEFAULT NULL AFTER `id`,
ADD INDEX `fk_manifest_user_client1_idx` (`user_client_id` ASC);
;

ALTER TABLE `freightmate`.`manifest` 
ADD CONSTRAINT `fk_manifest_user_client1`
  FOREIGN KEY (`user_client_id`)
  REFERENCES `freightmate`.`user_client` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
