# Delete old artifacts from build jobs - the assets we need are uploaded to AWS anyway
name: Remove old artifacts

on:
  push:
    branches:
      - master
      - development

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '2 weeks'
          skip-tags: true
